# -*- coding: utf-8 -*-
"""bert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KvqYE5zlBSAhJpPxH21QRZvYtjDV8QaX
"""

import numpy as np
import pandas as pd
import pip
import torch

df = pd.read_csv(r"C:\Users\Shreya\OneDrive\Desktop\final_year_project\cleaned_data (1).csv")
df=df.dropna()
print(df['Label'].value_counts())

from transformers import AutoTokenizer, AutoModel


tokenizer = AutoTokenizer.from_pretrained("Hate-speech-CNERG/dehatebert-mono-english")
model = AutoModel.from_pretrained("Hate-speech-CNERG/dehatebert-mono-english")

tokenized = df['text'].apply((lambda x: tokenizer.encode(x, add_special_tokens=True,max_length=40,truncation=True )))

max_len = 0
for i in tokenized.values:
  #print(len(i))
  if len(i) > max_len:
    max_len = len(i)

padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])


attention_mask = np.where(padded != 0, 1, 0)
#print(attention_mask[0])
attention_mask.shape

input_ids = torch.tensor(padded)
attention_mask = torch.tensor(attention_mask)

with torch.no_grad():
  last_hidden_states =model(input_ids, attention_mask=attention_mask)

"""prediction model"""

from nltk.corpus import stopwords   # to get collection of stopwords
from sklearn.model_selection import train_test_split       # for splitting dataset
from tensorflow.keras.models import Sequential     # the model
from tensorflow.keras.layers import Embedding, LSTM, Dense,Dropout,Bidirectional
from tensorflow.keras.callbacks import ModelCheckpoint   # save model
from tensorflow.keras.models import load_model   # load saved model
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score, precision_score, recall_score
import re
import nltk

bertembedding=last_hidden_states[0][:,11,:].numpy()
print(bertembedding)

bertembedding2 = bertembedding.reshape(-1, 768, 1)
print((bertembedding2.shape))
print(bertembedding2)

y = df['Label']

y = np.array(list(map(lambda x: 1 if x=="cyberbullying" else 0, y)))

X_features, Y_features, X_labels, Y_labels = train_test_split(bertembedding2, y,  test_size=0.5,random_state=50)

model_bert = Sequential()
model_bert.add(Bidirectional(LSTM(60, return_sequences=True)))
model_bert.add(Dropout(0.3))
model_bert.add(Bidirectional(LSTM(20)))
model_bert.add(Dropout(0.2))
model_bert.add(Dense(20, activation='relu'))
model_bert.add(Dropout(0.4))
model_bert.add(Dense(1, activation='sigmoid'))
model_bert.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

history=model_bert.fit(X_features, X_labels,batch_size=100, epochs = 50)

from sklearn.metrics import classification_report
y_pred = model_bert.predict(Y_features)
y_predN=np.round(y_pred)
print(classification_report(Y_labels, y_predN))

train_loss = history.history['loss']
train_acc = history.history['accuracy']
epochs = range(0,100)
plt.plot(epochs, train_loss, 'g', label='Training loss')
plt.plot(epochs,train_acc,'r', label='train accuracy')
plt.title('Training  loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt


fpr, tpr, thresholds = roc_curve(Y_labels, y_pred)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, color='blue', label='ROC curve (AUC = %0.2f)' % roc_auc)
plt.plot([1, 1], [0, 1], color='red', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic (ROC) curve')
plt.legend(loc="lower right")
plt.show()